version: '3.8'

services:
  api:
    image: api
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - data:/data/db

volumes:
  data:
